### ISSUE TITLE
Potential mentor seeks page for 2020

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC19/gsoc-2019#2]
I'm a potential mentor for a 2020 Boost GSoC Project.

Does anyone know a place where I can write the potential project description?

Thanks and kind regards, Chris

**Comment by mloskot** [comment]
Boost documents related to GSoC are collected in the superproject wiki, see links in table of contents on the left hand site here https://github.com/boostorg/boost/wiki

More specifically, see https://github.com/boostorg/boost/wiki/Google-Summer-of-Code%3A-Overview says:

> Potential mentors may add pre-canned project ideas with programming competency tests to this page below as GSoC approaches. 

I think it is also a good idea to introduce yourself as potential GSoC 2020 mentor on the Boost developers mailing list, https://lists.boost.org/boost, where the wider community as well as David Bellot, @yimyom, our GSoC admin, will have chance to react.

By the way, there is active Boost community here https://cpplang.slack.com (details at https://cppalliance.org/slack/), #boost and #boost-users channels

I hope it helps.

**Comment by ckormanyos** [comment]
Thank you very much Mat. That is awesome.

I'm a three-time past mentor, so I hope I can contribute again. I was not sure where to start.

Kind regards, Chris

**Comment by mloskot** [comment]
Great! If you have any further questions, I think, the mailing list is the best bet.
